### ISSUE TITLE
Game doesn't work

### ISSUE THREAD

**Issue by WaffleLapkin** [joywards/amazeing#2]
For some reason, the game doesn't work on my computer.

After running `cargo run --release` the game only shows this window:
![image](https://user-images.githubusercontent.com/38225716/66663011-8dae6200-ec52-11e9-851f-186561142aab.png)

And the only one hotkey that works is `esc` that closes the window.

Some information:
- It's Arch Linux
- I have `sdl2` installed

How can I figure out what is going wrong?

**Comment by kalabukdima** [comment]
Oh, it seems that it works just fine! You just need to press <kbd>Enter</kbd> to start playing the only unlocked level. I'm sorry that I forgot to mention this in the readme. I'll fix it ASAP.
Thanks for reaching out about this problem! I hope you will enjoy your experience and probably contribute to the project!

**Comment by WaffleLapkin** [comment]
Oh, that was so easy xD thanks, the game now works just fine!
